### ISSUE TITLE
作者，您好，我进行多标签训练的时候，始终只有前面两个类别有值，请问您知道是什么其他原因导致了这个问题吗，我在loading.py里面修改了数据加载方式如下。感谢回复，不胜感激

### ISSUE THREAD

**Issue by DaGuangDaGuang** [dyzy41/ChangeCLIP#19]
![image](https://github.com/user-attachments/assets/2c8b6a86-3097-4999-889e-e197c673a6a8)
![image](https://github.com/user-attachments/assets/ea3c5553-3b60-4278-b3cf-83b0fbb571c6)
![image](https://github.com/user-attachments/assets/590b4cdf-6c49-4fb1-bf8d-41648055fd6f)

**Comment by qilong164765913** [comment]
您好，请问解决了吗 @DaGuangDaGuang ，因为最近我们也在准备多标签的训练工作，想问一下您这边是怎么解决的

**Comment by dyzy41** [comment]
如果是多分类的样本，可以看一下这一行，https://github.com/dyzy41/ChangeCLIP/blob/5389e8f8413fdcec39155025cc8aa6d258d167f0/mmseg/datasets/transforms/loading.py#L125C9-L125C25。另外prompt的构建部分应该需要稍微修改，这块你可以自己尝试，有问题再进行提问。

**Comment by qilong164765913** [comment]
> 如果是多分类的样本，可以看一下这一行，[https://github.com/dyzy41/ChangeCLIP/blob/5389e8f8413fdcec39155025cc8aa6d258d167f0/mmseg/datasets/transforms/loading.py#L125C9-L125C25。另外prompt的构建部分应该需要稍微修改，这块你可以自己尝试，有问题再进行提问。](https://github.com/dyzy41/ChangeCLIP/blob/5389e8f8413fdcec39155025cc8aa6d258d167f0/mmseg/datasets/transforms/loading.py#L125C9-L125C25%E3%80%82%E5%8F%A6%E5%A4%96prompt%E7%9A%84%E6%9E%84%E5%BB%BA%E9%83%A8%E5%88%86%E5%BA%94%E8%AF%A5%E9%9C%80%E8%A6%81%E7%A8%8D%E5%BE%AE%E4%BF%AE%E6%94%B9%EF%BC%8C%E8%BF%99%E5%9D%97%E4%BD%A0%E5%8F%AF%E4%BB%A5%E8%87%AA%E5%B7%B1%E5%B0%9D%E8%AF%95%EF%BC%8C%E6%9C%89%E9%97%AE%E9%A2%98%E5%86%8D%E8%BF%9B%E8%A1%8C%E6%8F%90%E9%97%AE%E3%80%82)

好的感谢您的回答，我现在有time1和time2的两个多分类标签，类似于SECOND数据集这种格式，我需要把他们处理成一个标签作为训练数据哈，方便问下该怎么处理呢，是直接把time2的label拿来用就可以了吗
