### ISSUE TITLE
关于图片训练尺寸的质疑

### ISSUE THREAD

**Issue by LiiDy** [dyzy41/ChangeCLIP#2]
我尝试复现了你们的代码，使用的config为你们百度网盘所发布的，发现最后ChangeCLIP-RN50在levir数据集上的IoU为84.1，距离论文中给出的85.2相差1.1。我发现，你们在论文中提到，你们将levir原本大小为1024*1024的训练数据裁剪成了256*256的数据。对于遥感图像来说，尺度变小，精度大概率会上升。因此我能否认为这1.1的IoU提升来源于这个裁剪图片的策略？同时，我还希望你们能够提供裁剪之后的levir数据集供开发者们进行验证。

**Comment by dyzy41** [comment]
1.对LEVIR-CD数据集的切分方法：首先选定切分尺寸为256，overlap为64，由于这个尺寸不能正好覆盖1024x1024，因此多余的区域，以大图为边界进行镜像填充。最终切出来的数据量为文中所示。
2. 文章中LEVIR-CD精度指标推理测试细节：我对测试集也做了同样的切分，因此在做测试的时候，首先对256x256大小的切片进行预测。然后依照原始的切分方法将预测结果反向还原成大图，进行精度计算。
3. 这个切分方法是否对test结果有提升我没有测试，这个只是采用了常规的策略，我在文中有提及。
4. 你按照tools/general/merge_data.py的合并策略，可以写出来数据切分生成的代码。
5. 实际上我测试过我上述第2点的测试策略，这样的实际上会带来精度降低。如果直接对1024采用256x256大小的滑动窗口预测推理，计算得到的精度会更高。
