### ISSUE TITLE
关于优化器和迭代次数的参数设置问题

### ISSUE THREAD

**Issue by LiiDy** [dyzy41/ChangeCLIP#3]
在你们公开的config代码中，优化器的停止iteration为20000，但是你们设置迭代次数一共为40000iterations。我查看了你们提供的log，在20000iteration后，学习率全为0。因此我想知道你们这么做的用意是什么？

**Comment by dyzy41** [comment]
谢谢你提出这个问题，这的确是我的参数设置的一个错误，你可以将end修改为max_iters

**Comment by LiiDy** [comment]
好的，感谢你的回复。同时，我还很好奇，你是否进行过end和max_iters均为40000的实验。是不是你发现了，模型在20000时就已经拟合？

**Comment by dyzy41** [comment]
没有，修改为正确的参数，可能会训练得到更好的精度，也有可能过拟合，你可以尝试训练一下
